<a href="https://colab.research.google.com/github/LucasFelip/Ativ_A2_Numpy_e_Pandas/blob/main/%5BAtiv%5D_A2_Numpy_e_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

1 - Crie um array numpy de tamanho 7x7 com valores aleatórios inteiros entre 1 e 100 (inclusive). Em seguida, encontre o valor máximo e o valor mínimo em cada linha do array.

In [ ]:
import numpy as np

np.random.seed(40)
arr = np.random.randint(1, 101, size=(7,7))
max_por_linha = np.max(arr, axis=1)
min_por_linha = np.min(arr, axis=1)

print("Array:")
print(arr)
print("\nValor máximo por linha:")
print(max_por_linha)
print("\nValor mínimo por linha:")
print(min_por_linha)

Array:
[[ 71  92   8  38  57  51  66]
 [ 13  72  20  32  75  56  84]
 [ 60  92  74  97  50  54  74]
 [  9  53  31  80  15  93  59]
 [ 75  23   4  92 100  72  56]
 [ 84  29  14  38  83  51  80]
 [ 68  31  61  45  47  88  44]]

Valor máximo por linha:
[ 92  84  97  93 100  84  88]

Valor mínimo por linha:
[ 8 13 50  9  4 14 31]


2 - Crie um array numpy de tamanho 6x5 com valores aleatórios entre -5 e 5 (inclusive). Em seguida, normalize o array, ou seja, subtraia a média de cada coluna e divida pelo desvio padrão.

In [ ]:
import numpy as np

np.random.seed(40)
arr = np.random.uniform(low=-5, high=5, size=(6,5))
arr_norm = (arr - np.mean(arr, axis=0)) / np.std(arr, axis=0)

print("Array:")
print(arr)
print("\nArray normalizado:")
print(arr_norm)

Array:
[[-0.92312972 -4.4463396   2.88534877 -2.12694815 -0.49649413]
 [-1.96087695  0.26399524  1.23812213  2.76775458  1.86241645]
 [ 4.80938863  1.00816092  3.1396852   2.08645152 -4.7246532 ]
 [ 4.04267217 -0.50095149 -3.81075346  3.35300176 -2.97751774]
 [-3.25797329 -0.5085292   1.69794781  4.57399109  3.33333251]
 [ 0.08309965  1.30023548  3.35034686 -0.52668355  2.62290474]]

Array normalizado:
[[-0.46508106 -2.08674111  0.59704166 -1.65488001 -0.14592152]
 [-0.81263672  0.39178233 -0.07263407  0.46842508  0.64874253]
 [ 1.45481733  0.78335366  0.70044148  0.17287818 -1.57029344]
 [ 1.19803355 -0.01072374 -2.12524138  0.72230329 -0.9817227 ]
 [-1.24705194 -0.01471105  0.11430687  1.25196423  1.14426115]
 [-0.12808115  0.9370399   0.78608543 -0.96069077  0.90493398]]


3 - Crie um array numpy de tamanho 8x8 com valores aleatórios entre 0 e 1 (exclusive). Em seguida, crie um novo array onde todos os valores menores que 0.5 são substituídos por 0 e todos os valores maiores ou iguais a 0.5 são substituídos por 1.

In [ ]:
import numpy as np

np.random.seed(40)
arr = np.random.rand(8,8)
arr_bin = np.where(arr < 0.5, 0, 1)

print("Array:")
print(arr)
print("\nArray binarizado:")
print(arr_bin)

Array:
[[0.40768703 0.05536604 0.78853488 0.28730518 0.45035059 0.30391231
  0.52639952 0.62381221]
 [0.77677546 0.68624165 0.98093886 0.60081609 0.81396852 0.70864515
  0.02753468 0.90426722]
 [0.44990485 0.11892465 0.83530018 0.20224823 0.17420267 0.44914708
  0.66979478 0.95739911]
 [0.83333325 0.50830996 0.63002355 0.83503469 0.44733165 0.76229047
  0.63692224 0.36229589]
 [0.01457455 0.54198489 0.31815548 0.14499035 0.54889195 0.18748127
  0.39898148 0.24003821]
 [0.03665485 0.56854476 0.9227648  0.17905511 0.70307767 0.7200128
  0.03106402 0.58282531]
 [0.6976776  0.90985347 0.96669799 0.83572953 0.95112137 0.50632553
  0.19449838 0.06964475]
 [0.92579567 0.39132648 0.40817073 0.17090505 0.13234514 0.50998058
  0.34074415 0.4569195 ]]

Array binarizado:
[[0 0 1 0 0 0 1 1]
 [1 1 1 1 1 1 0 1]
 [0 0 1 0 0 0 1 1]
 [1 1 1 1 0 1 1 0]
 [0 1 0 0 1 0 0 0]
 [0 1 1 0 1 1 0 1]
 [1 1 1 1 1 1 0 0]
 [1 0 0 0 0 1 0 0]]


4 - Crie um array numpy de tamanho 10x5 com valores aleatórios inteiros entre 0 e 9 (inclusive). Em seguida, conte quantas vezes cada número aparece em todo o array.

In [ ]:
import numpy as np

np.random.seed(42)
arr = np.random.randint(0, 10, (10,5))

unique, counts = np.unique(arr, return_counts=True)

print("Array:")
print(arr)
print("\nContagem:")
print(dict(zip(unique, counts)))

Array:
[[6 3 7 4 6]
 [9 2 6 7 4]
 [3 7 7 2 5]
 [4 1 7 5 1]
 [4 0 9 5 8]
 [0 9 2 6 3]
 [8 2 4 2 6]
 [4 8 6 1 3]
 [8 1 9 8 9]
 [4 1 3 6 7]]

Contagem:
{0: 2, 1: 5, 2: 5, 3: 5, 4: 7, 5: 3, 6: 7, 7: 6, 8: 5, 9: 5}


5 - Utilize o dataset "Iris" (disponível em https://archive.ics.uci.edu/ml/datasets/iris) para realizar a seguinte tarefa: crie um array numpy apenas com os valores da largura da sépala de todas as flores da espécie Iris-versicolor. Em seguida, calcule a média e o desvio padrão desses valores.

In [ ]:
import numpy as np
import urllib.request

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
response = urllib.request.urlopen(url)
iris_data = response.read().decode('utf-8')
iris_data = iris_data.split('\n')[:-1]

versicolor_sepal_width = []
for row in iris_data:
    iris = row.split(',')
    if len(iris) == 5 and iris[4] == 'Iris-versicolor':
        versicolor_sepal_width.append(float(iris[1]))

versicolor_sepal_width = np.array(versicolor_sepal_width)

mean = np.mean(versicolor_sepal_width)
std = np.std(versicolor_sepal_width)

print("Média: {:.2f}".format(mean))
print("Desvio padrão: {:.2f}".format(std))

Média: 2.77
Desvio padrão: 0.31


# Pandas

1 - Crie uma Series com os valores [10, 20, 30, 40, 50], indexada por ['a', 'b', 'c', 'd', 'e'].

In [ ]:
import pandas as pd

data = [10, 20, 30, 40, 50]
index = ['a', 'b', 'c', 'd', 'e']
s = pd.Series(data, index=index)

print(s)

a    10
b    20
c    30
d    40
e    50
dtype: int64


2 - Crie um DataFrame com as colunas 'nome', 'idade' e 'cidade', contendo as seguintes informações: ('João', 30, 'São Paulo'), ('Maria', 25, 'Rio de Janeiro'), ('Pedro', 35, 'Belo Horizonte').

In [ ]:
import pandas as pd

data = {'nome': ['João', 'Maria', 'Pedro'],
        'idade': [30, 25, 35],
        'cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte']}
df = pd.DataFrame(data)

print(df)

    nome  idade          cidade
0   João     30       São Paulo
1  Maria     25  Rio de Janeiro
2  Pedro     35  Belo Horizonte


3 - Crie um Index com as datas '2022-01-01', '2022-01-02' e '2022-01-03'.

In [ ]:
import pandas as pd

dates = ['2022-01-01', '2022-01-02', '2022-01-03']
idx = pd.Index(dates)

print(idx)

Index(['2022-01-01', '2022-01-02', '2022-01-03'], dtype='object')


4 - Adicione uma nova coluna chamada 'salário' ao DataFrame do exercício 2, contendo as informações [5000, 4000, 6000] para as linhas 'João', 'Maria' e 'Pedro', respectivamente.

In [ ]:
import pandas as pd

df = pd.DataFrame(data)

df['salário'] = [5000, 4000, 6000]

print(df)

    nome  idade          cidade  salário
0   João     30       São Paulo     5000
1  Maria     25  Rio de Janeiro     4000
2  Pedro     35  Belo Horizonte     6000


5 - Selecione do DataFrame do exercício 4 apenas as linhas com idade maior ou igual a 30 anos.

In [25]:
df_above_30 = df[df['idade'] >= 30]

print(df_above_30)

    nome  idade          cidade  salário
0   João     30       São Paulo     5000
2  Pedro     35  Belo Horizonte     6000
